# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site Settings
title: "GDG DevFest Birgunj 2014"
email: "dipesh009@gmail.com"
description: "GDG DevFest is a set of events all around the world"
baseurl: "/zeppelin"
url: "http://gdgbirgunj.github.io"
permalink: "/blog/:title"

googleAnalyticsSiteUrl: "gdgirgunj.github.io"

# Organizer Info
organizerName: "GDG Birgunj"
organizerAlternateName: "Google Developer Group Space Coast"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "dipesh009@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://gdgbirgunj.blogspot.com/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, developers, Birgunj"
twitterAccount: "@gdgbirgunj"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://docs.google.com/forms/d/1AqI_PUYF1hPD6aYIw4R8pPDmHt0X08Oi6JFEIirsOG4/edit"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
# - {permalink: "/schedule/", text: "Schedule"}
# - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
 - {link: "https://developers.google.com", text: "Developers"}
bottomNavigationLinks:
 - {link: "https://docs.google.com/forms/d/1GWy11zS3c6Er9yxxmR62ygXL9jtgCnXngVZGWZWbxx8/viewform?usp=send_form", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "https://docs.google.com/forms/d/1GWy11zS3c6Er9yxxmR62ygXL9jtgCnXngVZGWZWbxx8/viewform?usp=send_form", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "GDG DevFest <typeout> 2014"
eventDate: "November 22, 2014"
typeoutTextValues: '"", "Birgunj", "Nepal"'
typeoutFallback: "Birgunj"
heroButtons:
 - {link: "https://docs.google.com/forms/d/1GWy11zS3c6Er9yxxmR62ygXL9jtgCnXngVZGWZWbxx8/viewform?usp=send_form", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Ticket Info"}

# About Block
aboutTitle: "About GDG Birgunj DevFest"
aboutBlock:
 - {title: "Tech Talks", image: "conference.jpg",
    text: "Come hear the latest updates on Android L, Android TV, Android Wear, Google Glass, and Android Studio." }
 - {title: "Design Sprint", image: "workshop.jpg",
    text: "The design sprint is a process for prototyping and testing any product. This process was just made public by Google Ventures and Google[x] in 2014." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "150", specialCharacter: "+", info: "attendees", detail: "Developers, Designers, and Business"}
 - {count: "3", specialCharacter: "", info: "hours", detail: "of Android Demos and presentations"}
 - {count: "4", specialCharacter: "+", info: "hours", detail: "of collaboration, brainstorming, and innovation"}
 - {count: "4", specialCharacter: "+", info: "speakers", detail: "experienced in Google technologies"}

# Latest News Block
latestNewsTitle: "Latest news"

# Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 0
rockstarSpeakersTitle: "Speakers TBA..."
rockstarSpeakersButtonText: "Speaker Details"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Birgunj"
eventLocationLink: "http://www.fit.edu/"
eventStreetAddress: ".."
eventAddressLocality: ".."
eventAddressLocalityRegion: ".."
eventPostalCode: "44300"
eventAddressCountry: "Nepal"
eventStartTime: "2014-11-22T09:00"
eventDoorTime: "09:00"
eventEndTime: "2014-11-22T18:00"
eventPlaceCoordinates: "27.014799, 84.878801"
mapCenterCoordinates: "27.014799, 84.878801"
mapMobileCenterCoordinates: "27.014799, 84.878801"

# Venue Block
venueBlockTitle: "Venue"
venueTitle: "TBA"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
#venueFeatures: ["Huge cinema screen", "Bose surround sound system", "Mobile device 'document' camera"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=900"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://blogspot.us9.list-manage1.com/subscribe?u=2aa7f76f46d9294e3dd42f1cb&id=e7dde3b5e8"
subscribeInfo: "Registration will be open in early November. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsInfoTitle: "Ticket Information"
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all tech talks, coffee brakes, and the design sprint. Advanced RSVP is required."
ticketsOffers:
 -
  name: "DevFest Birgunj"
  price: "TBA"
  ticketsNumber: "150"
  ribbon: "-100%"
  buyButtonLink: "http://gdgbirgunj.blogspot.com/"
  buyButtonText: "Coming Soon!"
  ticketContentList: ["Registration will open soon!", "Limit: 150 attendees."]
  validFrom: "2014-11-01T00:00"
  validThrough: "2014-11-17T19:00"

# Footer
socialLinks:
 - {link: "https://plus.google.com/112807703637841959875", icon: "google-plus"}
 - {link: "https://twitter.com/gdgbirgunj", icon: "twitter"}
 - {link: "https://facebook.com/gdgbirgunj", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://gdgbirgunj.blogspot.com", text: "GDG Birgunj"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
    - {link: "http://google.com/+DipeshKumar", text: "Dipesh Kumar"}
    - {link: "mailto:dipesh009@gmail.com", text: "dipesh009@gmail.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}
# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: "devfestbirgunj"

# Speakers List Block
showSessions: false
thumbnailsFolder: /img/speakers/

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google Developer Group (GDG) Birgunj is a technology user group that meets to discuss the latest Google Technologies, Tools, SDKs, and APIs. The focus is on learning about the broad spectrum of technologies provided by Google and finding ways that these technologies can be applied. This includes discussions of the technologies from a number of angles (start ups, corporations, and individuals).
<br/><br/>
Here are a few of the topics that we have covered so far:<br/>
Android, Chrome, Chrome OS / Chromium, Google App , Google Play, Google Maps, Android Design Guidelines, Web Components, Ingress, Android Studio, and more.
<br/><br/>
In addition to regular speaker focused meetings, we also organize code camps, idea camp, Developers Meetup and assist with the local institutions and Business Organization.
<br/><br/>
The group is free to attend and open to all who are interested in discussing and learning more about software development with Google Tools and Technologies.
<br/><br/>
If you would like to stay up to date with events and activities of the group, please follow us on Google+. If you would like to take part in discussions about the group, future events, and future content, please join the GDG Birgunj community linked from our About page on Google+."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "27.014799, 84.878801"
logisticsMapMobileCenterCoordinates: "27.014799, 84.878801"

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around the Birgunj City"
directionDetailsCards:
 - {title: "From the Airport", information: 'The Simara Airport is just a 25 minute drive (20 Kilo Meters to the North) from Birgunj.'}
 - {title: "Public Transit", information: 'Public transportation in Birgunj is ineffective and difficult to use, especially on weekends. Rental cars from the airport are recommended.'}
 - {title: "Hotels", information: 'Birgunj has many good hotels.  See below for more details.'}
directionDetailsWideCards: 
 -
  title: "Details"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/112807703637841959875", text: "Hotal Vishuwa"}
     - {link: "https://plus.google.com/112807703637841959875", text: "Hotel Pujan"}
     - {link: "https://plus.google.com/112807703637841959875", text: "Makalu"}
     - {link: "https://plus.google.com/112807703637841959875", text: "Hotel Suraj"}
   - 
    title: "Travel and Site Seeing"
    links:
     - {link: "http://www.forestrynepal.org/resources/pas/parsa-wildlife-reserve", text: "Parsa WildLife Reserve"}
     - {link: "http://www.htpldryport.com/", text: "Dry Port"}
     - {link: "https://www.google.com.np/maps/search/Ghadiyarwa+Pokhari/@27,84.866667,7z/data=!4m5!2m4!3m3!1sGhadiyarwa+Pokhari!2sBirgunj!3s0x39935446b21c98cb:0x42938e30ff4f6cb5", text: "Ghadiyarwa Pokhari"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didnâ€™t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
