# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site Settings
title: "Android DevFest Season 2014"
email: "organizer@gdgspacecoast.org"
description: "GDG DevFest is a set of events all around the world"
baseurl: "/zeppelin"
url: "http://gdg-space-coast.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-41029375-7"
googleAnalyticsSiteUrl: "gdg-space-coast.github.io"

# Organizer Info
organizerName: "GDG Space Coast"
organizerAlternateName: "Google Developer Group Space Coast"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "organizer@gdgspacecoast.org"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://gdgspacecoast.org/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, developers, Space Coast"
twitterAccount: "@gdgspacecoast"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://docs.google.com/forms/d/1GWy11zS3c6Er9yxxmR62ygXL9jtgCnXngVZGWZWbxx8/viewform?usp=send_form"
c4sponsorsUrl: "https://docs.google.com/forms/d/1H3lMjgsrccU1PXCzLKvSzGU6eBmrdZJ8B976tJmYfCk/viewform?usp=send_form"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
# - {permalink: "/schedule/", text: "Schedule"}
# - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
 - {link: "https://developers.google.com", text: "Developers"}
bottomNavigationLinks:
 - {link: "https://docs.google.com/forms/d/1GWy11zS3c6Er9yxxmR62ygXL9jtgCnXngVZGWZWbxx8/viewform?usp=send_form", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "https://docs.google.com/forms/d/1GWy11zS3c6Er9yxxmR62ygXL9jtgCnXngVZGWZWbxx8/viewform?usp=send_form", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Android DevFest <typeout> 2014"
eventDate: "October 18th, 2014"
typeoutTextValues: '"", "Melbourne", "Florida Tech"'
typeoutFallback: "Space Coast"
heroButtons:
 - {link: "https://docs.google.com/forms/d/1GWy11zS3c6Er9yxxmR62ygXL9jtgCnXngVZGWZWbxx8/viewform?usp=send_form", text: "Become a speaker"}
 - {permalink: "/#tickets", text: "Ticket Info"}

# About Block
aboutTitle: "About Android DevFest"
aboutBlock:
 - {title: "Tech Talks", image: "conference.jpg",
    text: "Come hear the latest updates on Android L, Android TV, Android Wear, Google Glass, and Android Studio." }
 - {title: "Design Sprint", image: "workshop.jpg",
    text: "The design sprint is a process for prototyping and testing any product. This process was just made public by Google Ventures and Google[x] in 2014." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "110", specialCharacter: "+", info: "attendees", detail: "Developers, Designers, and Business"}
 - {count: "3", specialCharacter: "", info: "hours", detail: "of Android Demos and presentations"}
 - {count: "4", specialCharacter: "+", info: "hours", detail: "of collaboration, brainstorming, and innovation"}
 - {count: "3", specialCharacter: "+", info: "speakers", detail: "experienced in Google technologies"}

# Latest News Block
latestNewsTitle: "Latest news"

# Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 0
rockstarSpeakersTitle: "Speakers TBA..."
rockstarSpeakersButtonText: "Speaker Details"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Florida Institute of Technology"
eventLocationLink: "http://www.fit.edu/"
eventStreetAddress: "150 W University Blvd"
eventAddressLocality: "Melbourne"
eventAddressLocalityRegion: "Florida"
eventPostalCode: "32901"
eventAddressCountry: "USA"
eventStartTime: "2014-10-04T11:00"
eventDoorTime: "10:30"
eventEndTime: "2014-10-04T20:00"
eventPlaceCoordinates: "28.064459,-80.622979"
mapCenterCoordinates: "28.064459,-80.622979"
mapMobileCenterCoordinates: "28.064459,-80.622979"

# Venue Block
venueBlockTitle: "Venue"
venueTitle: "Olin Engineering Complex"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueFeatures: ["Huge cinema screen", "Bose surround sound system", "Mobile device 'document' camera"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=900"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open in early September. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsInfoTitle: "Ticket Information"
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all tech talks, coffee brakes, and the design sprint. Advanced RSVP is required."
ticketsOffers:
 -
  name: "1 day"
  price: "Free!"
  ticketsNumber: "110"
  ribbon: "-100%"
  buyButtonLink: "http://www.meetup.com/GDGSpaceCoast/events/208445302/"
  buyButtonText: "RSVP Now"
  ticketContentList: ["Registration is open!", "Limit: 110 attendees."]
  validFrom: "2014-09-20T14:00"
  validThrough: "2014-10-17T19:00"

# Footer
socialLinks:
 - {link: "https://plus.google.com/+GDGSpaceCoastOrg", icon: "google-plus"}
 - {link: "https://twitter.com/gdgspacecoast", icon: "twitter"}
 - {link: "https://www.facebook.com/gdgspacecoast", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://gdgspacecoast.org", text: "GDG Space Coast"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:organizer@gdgspacecoast.org", text: "organizer@gdgspacecoast.org"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: "devfestspacecoast"

# Speakers List Block
showSessions: false
thumbnailsFolder: /img/speakers/

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google Developer Group (GDG) Space Coast is a technology user group that meets to discuss the latest Google Technologies, Tools, SDKs, and APIs. The focus is on learning about the broad spectrum of technologies provided by Google and finding ways that these technologies can be applied. This includes discussions of the technologies from a number of angles (start ups, corporations, and individuals).
<br/><br/>
Here are a few of the topics that we have covered so far:<br/>
Android, Chrome, Chrome OS / Chromium, Google App Engine, Google Play Games Services, GWT, Google Maps for Android, Android Design Guidelines, Dart, AngularJS, Cloud Endpoints, Chrome Packaged Apps, Polymer, Web Components, Ingress, Android Studio, and more.
<br/><br/>
In addition to regular speaker focused meetings, we also organize code camps, hackathons, and assist with the local TrepHub and Startup Weekend events.
<br/><br/>
The group is free to attend and open to all who are interested in discussing and learning more about software development with Google Tools and Technologies.
<br/><br/>
If you would like to stay up to date with events and activities of the group, please follow us on Google+. If you would like to take part in discussions about the group, future events, and future content, please join the GDG Space Coast community linked from our About page on Google+.
<br/><br/>
Disclaimer: GDG Space Coast is an independent group; our activities and the opinions expressed here should in no way be linked to Google, the corporation."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "28.064459,-80.622979"
logisticsMapMobileCenterCoordinates: "28.064459,-80.622979"

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around the Space Coast"
directionDetailsCards:
 - {title: "From the Airport", information: 'The Melbourne International Airport is just a 10 minute drive (2.5 miles to the south) from Florida Tech. If you need to use the Orlando Airport, then the drive will be 1 hour.'}
 - {title: "Public Transit", information: 'Public transportation in Melbourne is ineffective and difficult to use, especially on weekends. Rental cars from the airport are recommended.'}
 - {title: "Hotels", information: 'Melbourne has many good hotels. There are beachfront hotels with a view or hotels close to the airport for your convenience. See below for more details.'}
directionDetailsWideCards: 
 -
  title: "Details"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "http://www.ihg.com/crowneplaza/hotels/us/en/melbourne/mlboc/hoteldetail?cm_mmc=GoogleMaps-_-cp-_-USEN-_-mlboc", text: "Crowne Plaza Melbourne-Oceanfront"}
     - {link: "http://www.doubletreemelbournebeach.com/", text: "DoubleTree Suites by Hilton Melbourne Beach Oceanfront"}
     - {link: "http://www3.hilton.com/en/hotels/florida/hilton-melbourne-rialto-place-MLBMHHF/index.html", text: "Hilton Melbourne Rialto Place"}
     - {link: "http://www.marriott.com/hotels/travel/mlbap-residence-inn-melbourne/", text: "Residence Inn Melbourne"}
   - 
    title: "Travel"
    links:
     - {link: "http://www.mlbair.com/", text: "Melbourne International Airport"}
     - {link: "http://www.orlandoairports.net/", text: "Orlando International Airport"}
     - {link: "http://www.orlandosanfordairport.com/", text: "Orlando Sanford International Airport"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didnâ€™t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
